/**
 * @fileoverview Database Access Layer using SQLite.
 *
 * Problem: We need a way to store chat history, sessions, and generated documents (artifacts)
 * so that they persist even if the server restarts.
 *
 * Solution: Use SQLite, a lightweight, file-based database that is perfect for
 * hackathons and local development because it doesn't require a complex setup.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { Database, open } from "sqlite";
import sqlite3 from "sqlite3";
import type {
  ArtifactKind,
  Mode,
  Role,
  Source
} from "@the-architect/shared-types";

// Type alias for our database connection
export type AppDatabase = Database;

/**
 * Data Models
 * These represent the rows in our database tables.
 */

export type SessionRecord = {
  id: string;
  title: string | null;
  mode: Mode;
  tech_stack: string | null; // JSON string
  created_at: string;
  updated_at: string;
};

export type MessageRecord = {
  id: string;
  session_id: string;
  role: Role;
  content: string;
  transcript_source: Source;
  created_at: string;
};

export type ArtifactRecord = {
  id: string;
  session_id: string;
  kind: ArtifactKind;
  title: string;
  content_md: string;
  content_json: string;
  created_at: string;
};

/**
 * Input Types
 * Used when creating new records.
 */

export type CreateSessionInput = {
  id: string;
  mode: Mode;
  title?: string | undefined;
};

export type InsertMessageInput = {
  id: string;
  session_id: string;
  role: Role;
  content: string;
  transcript_source: Source;
};

export type CreateArtifactInput = {
  id: string;
  session_id: string;
  kind: ArtifactKind;
  title: string;
  content_md: string;
  content_json: string;
};

/**
 * Helper: Clean up the database file path string.
 */
function normalizeDatabasePath(databaseUrl: string): string {
  if (databaseUrl === ":memory:") {
    return databaseUrl;
  }

  if (databaseUrl.startsWith("sqlite://")) {
    return databaseUrl.slice("sqlite://".length);
  }

  if (databaseUrl.startsWith("file:")) {
    return databaseUrl.slice("file:".length);
  }

  return databaseUrl;
}

/**
 * Helper: Create the folder for the database file if it doesn't exist.
 */
async function ensureParentDirectory(dbPath: string) {
  if (dbPath === ":memory:") {
    return;
  }

  const parent = path.dirname(dbPath);
  await fs.mkdir(parent, { recursive: true });
}

/**
 * Problem: We need a reliable connection to the database.
 * Solution: Open the SQLite file, enable Write-Ahead Logging (WAL) for better performance,
 * and ensure Foreign Keys are enforced to keep data linked correctly.
 */
export async function openDatabase(databaseUrl: string): Promise<AppDatabase> {
  const dbPath = normalizeDatabasePath(databaseUrl);
  await ensureParentDirectory(dbPath);

  const db = await open({
    filename: dbPath,
    driver: sqlite3.Database
  });

  // Optimization: WAL mode allows reading and writing at the same time more efficiently.
  await db.exec("PRAGMA journal_mode = WAL;");
  // Performance: NORMAL sync is safe with WAL and avoids excessive fsync overhead.
  await db.exec("PRAGMA synchronous = NORMAL;");
  // Integrity: Ensure that if a session is deleted, we can't have "orphaned" messages.
  await db.exec("PRAGMA foreign_keys = ON;");

  return db;
}

/**
 * Problem: How do we create the tables the first time the app runs?
 * Solution: Run 'Migrations' (SQL scripts) that define the structure of our tables.
 */
export async function runMigrations(db: AppDatabase): Promise<void> {
  await db.exec(`
    -- Stores high-level chat sessions
    CREATE TABLE IF NOT EXISTS sessions (
      id TEXT PRIMARY KEY,
      title TEXT,
      mode TEXT NOT NULL CHECK (mode IN ('architect', 'planner', 'pitch')),
      tech_stack TEXT,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Stores individual messages within a session
    CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
      content TEXT NOT NULL,
      transcript_source TEXT NOT NULL CHECK (transcript_source IN ('voice', 'text')),
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (session_id) REFERENCES sessions(id)
    );

    -- Stores documents generated by the AI
    CREATE TABLE IF NOT EXISTS artifacts (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      kind TEXT NOT NULL CHECK (kind IN ('architecture', 'tasks', 'pitch')),
      title TEXT NOT NULL,
      content_md TEXT NOT NULL,
      content_json TEXT NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (session_id) REFERENCES sessions(id)
    );

    -- Tracks background jobs (like artifact generation)
    CREATE TABLE IF NOT EXISTS jobs (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      kind TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('pending', 'active', 'completed', 'failed')),
      error TEXT,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Indexes make searching for messages/artifacts by session ID much faster.
    CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id);
    CREATE INDEX IF NOT EXISTS idx_artifacts_session_id ON artifacts(session_id);

    -- Stores saved React Flow node positions for blueprint layout persistence
    CREATE TABLE IF NOT EXISTS blueprint_layouts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      node_id TEXT NOT NULL,
      x REAL NOT NULL,
      y REAL NOT NULL,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(session_id, node_id)
    );

    -- Stores incremental design summaries generated every N messages
    CREATE TABLE IF NOT EXISTS design_summaries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      summary TEXT NOT NULL,
      message_count INTEGER NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (session_id) REFERENCES sessions(id)
    );

    CREATE INDEX IF NOT EXISTS idx_blueprint_layouts_session ON blueprint_layouts(session_id);
    CREATE INDEX IF NOT EXISTS idx_design_summaries_session ON design_summaries(session_id);
  `);

  // Ensure new columns exist for existing databases (backward compatibility)
  await ensureColumnExists(db, "artifacts", "content_json", "TEXT");
  await ensureColumnExists(db, "sessions", "tech_stack", "TEXT");
}

/**
 * Helper: Safely add a column to a table if it doesn't already exist.
 */
async function ensureColumnExists(
  db: AppDatabase,
  tableName: string,
  columnName: string,
  columnDefinition: string
) {
  const rows = await db.all<{ name: string }[]>(
    `PRAGMA table_info(${tableName});`
  );

  if (rows.some((row) => row.name === columnName)) {
    return;
  }

  await db.exec(
    `ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${columnDefinition};`
  );
}

/**
 * CRUD Operations (Create, Read, Update, Delete)
 */

export async function createSession(
  db: AppDatabase,
  input: CreateSessionInput
): Promise<SessionRecord> {
  await db.run(
    `INSERT INTO sessions (id, title, mode, created_at, updated_at)
     VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
    input.id,
    input.title ?? null,
    input.mode
  );

  const row = await getSessionById(db, input.id);

  if (!row) {
    throw new Error("Failed to fetch created session");
  }

  return row;
}

export async function ensureSessionExists(
  db: AppDatabase,
  input: CreateSessionInput
): Promise<void> {
  const existing = await getSessionById(db, input.id);

  if (existing) {
    return;
  }

  await createSession(db, input);
}

export async function getSessionById(
  db: AppDatabase,
  sessionId: string
): Promise<SessionRecord | undefined> {
  return db.get<SessionRecord>(
    `SELECT id, title, mode, tech_stack, created_at, updated_at
     FROM sessions
     WHERE id = ?`,
    sessionId
  );
}

export async function updateSessionTechStack(
  db: AppDatabase,
  sessionId: string,
  techStackJson: string
): Promise<void> {
  await db.run(
    `UPDATE sessions 
     SET tech_stack = ?, updated_at = CURRENT_TIMESTAMP
     WHERE id = ?`,
    techStackJson,
    sessionId
  );
}

export async function insertMessage(
  db: AppDatabase,
  input: InsertMessageInput
): Promise<void> {
  await db.run(
    `INSERT INTO messages (id, session_id, role, content, transcript_source, created_at)
     VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
    input.id,
    input.session_id,
    input.role,
    input.content,
    input.transcript_source
  );
}

export async function listArtifactsBySession(
  db: AppDatabase,
  sessionId: string
): Promise<ArtifactRecord[]> {
  return db.all<ArtifactRecord[]>(
    `SELECT id, session_id, kind, title, content_md, content_json, created_at
     FROM artifacts
     WHERE session_id = ?
     ORDER BY created_at DESC`,
    sessionId
  );
}

export async function getArtifactById(
  db: AppDatabase,
  artifactId: string
): Promise<ArtifactRecord | undefined> {
  return db.get<ArtifactRecord>(
    `SELECT id, session_id, kind, title, content_md, content_json, created_at
     FROM artifacts
     WHERE id = ?`,
    artifactId
  );
}

export async function insertArtifact(
  db: AppDatabase,
  input: CreateArtifactInput
): Promise<void> {
  await db.run(
    `INSERT INTO artifacts (id, session_id, kind, title, content_md, content_json, created_at)
     VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
    input.id,
    input.session_id,
    input.kind,
    input.title,
    input.content_md,
    input.content_json
  );
}

/**
 * Problem: We need to track the status of background tasks (e.g., "Is the PDF generated yet?").
 * Solution: Use an 'upsert' (Update or Insert) to track job status in the database.
 */
export async function upsertJobStatus(
  db: AppDatabase,
  input: {
    id: string;
    session_id: string;
    kind: string;
    status: "pending" | "active" | "completed" | "failed";
    error?: string | null;
  }
): Promise<void> {
  await db.run(
    `INSERT INTO jobs (id, session_id, kind, status, error, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      ON CONFLICT(id) DO UPDATE SET
        status = excluded.status,
        error = excluded.error,
        updated_at = CURRENT_TIMESTAMP`,
    input.id,
    input.session_id,
    input.kind,
    input.status,
    input.error ?? null
  );
}

/**
 * Blueprint Layout Persistence
 */
export async function saveNodePositions(
  db: AppDatabase,
  sessionId: string,
  positions: Array<{ id: string; x: number; y: number }>
): Promise<void> {
  for (const pos of positions) {
    await db.run(
      `INSERT INTO blueprint_layouts (session_id, node_id, x, y, updated_at)
       VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
       ON CONFLICT(session_id, node_id) DO UPDATE SET
         x = excluded.x,
         y = excluded.y,
         updated_at = CURRENT_TIMESTAMP`,
      sessionId,
      pos.id,
      pos.x,
      pos.y
    );
  }
}

export async function getSavedNodePositions(
  db: AppDatabase,
  sessionId: string
): Promise<Array<{ id: string; x: number; y: number }>> {
  const rows = await db.all<Array<{ node_id: string; x: number; y: number }>>(
    `SELECT node_id, x, y FROM blueprint_layouts WHERE session_id = ? ORDER BY updated_at DESC`,
    sessionId
  );
  return rows.map((row) => ({ id: row.node_id, x: row.x, y: row.y }));
}

/**
 * Design Summary Management
 */
export type DesignSummaryRecord = {
  id: number;
  session_id: string;
  summary: string;
  message_count: number;
  created_at: string;
};

export async function insertDesignSummary(
  db: AppDatabase,
  input: {
    session_id: string;
    summary: string;
    message_count: number;
  }
): Promise<void> {
  await db.run(
    `INSERT INTO design_summaries (session_id, summary, message_count, created_at)
     VALUES (?, ?, ?, CURRENT_TIMESTAMP)`,
    input.session_id,
    input.summary,
    input.message_count
  );
}

export async function getLatestDesignSummary(
  db: AppDatabase,
  sessionId: string
): Promise<DesignSummaryRecord | undefined> {
  return db.get<DesignSummaryRecord>(
    `SELECT id, session_id, summary, message_count, created_at
     FROM design_summaries
     WHERE session_id = ?
     ORDER BY created_at DESC
     LIMIT 1`,
    sessionId
  );
}

export async function getSessionMessageCount(
  db: AppDatabase,
  sessionId: string
): Promise<number> {
  const row = await db.get<{ count: number }>(
    `SELECT COUNT(*) as count FROM messages WHERE session_id = ?`,
    sessionId
  );
  return row?.count ?? 0;
}

export async function getAllMessages(
  db: AppDatabase,
  sessionId: string
): Promise<Array<{ role: string; content: string; transcript_source: string; created_at: string }>> {
  return db.all(
    `SELECT role, content, transcript_source, created_at
     FROM messages
     WHERE session_id = ?
     ORDER BY created_at ASC`,
    sessionId
  );
}
